version: '3.8'

services:
  medical-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: medical-telegram-api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=medical_warehouse
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - REDIS_URL=redis://redis:6379
      - API_PORT=8000
      - ENVIRONMENT=development
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - medical-network

  redis:
    image: redis:7-alpine
    container_name: medical-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - medical-network

  postgres:
    image: postgres:15
    container_name: medical_warehouse_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: medical_warehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - medical-network

networks:
  medical-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: